### ISSUE TITLE
How to use the both onChange of react-hook-form and onChange of react-images-uploading

### ISSUE THREAD

**Issue by tinnguyen1296** [vutoan266/react-images-uploading#110]
Hi there,
I have upload image field using react-images-uploading and I want to check "required field" from react-hook-form for upload image field. But I cannot use onChange event from two
Please help me. Thanks.

**Comment by tinnguyen1296** [comment]
> Hi there, I have upload image field using react-images-uploading and I want to check "required field" from react-hook-form for upload image field. But I cannot use onChange event from two Please help me. Thanks.

I uploaded codesandbox --> https://codesandbox.io/s/eloquent-lake-j55q9

**Comment by vutoan266** [comment]
Hi @tinnguyen1296, have you resolved it? Because this is a Controlled component (it's different with uncontrolled components like <input />.. ) so you need to use Controller component of `react-hook-form` to wrap `react-images-uploading` component. you should refer here: https://react-hook-form.com/api/usecontroller/controller

**Comment by vutoan266** [comment]
Sorry for my late reply. Hope it is helpful for you, thank you!
