### ISSUE TITLE
upload to API accept multipart/form-data instead of application/json

### ISSUE THREAD

**Issue by tesshsu** [vutoan266/react-images-uploading#81]
Hi team,
Sorry again for one questions
The library once choice will send as in json format:
`uploads: Array(2)
0:
data_url: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD"
file: File
lastModified: 1604325396020
lastModifiedDate: Mon Nov 02 2020 14:56:36 GMT+0100 (中歐標準時間) {}
name: "4.jpg"
size: 83005
type: "image/jpeg"
webkitRelativePath: ""`

Will it possible add any parametre to change to **multipart/form-data** instead of application/json ?

Appreciate your help

**Comment by vutoan266** [comment]
Sorry I am late again :))) I miss notification because gmail does not send (or sent to spam hub) to me :(
Your requirement is changing the method of encoding to `multipart/form-data` but that not on my component side. You could change it in your `Request` function. Follow [this](https://stackoverflow.com/questions/35192841/how-do-i-post-with-multipart-form-data-using-fetch)
Feel free to ask me if you have any more questions.
